/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = { 'new' : null } |
  { 'limitedEdition' : null } |
  { 'sale' : null } |
  { 'bestseller' : null };
export type Category = { 'men' : null } |
  { 'unisex' : null } |
  { 'women' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : Category,
  'badge' : Badge,
  'imageIndex' : bigint,
  'priceCents' : bigint,
}
export interface _SERVICE {
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];